### ISSUE TITLE
`TypeError` with Jinja 2.10.1

### ISSUE THREAD

**Issue by SnoopJeDi** [nedbat/dinghy#1]
It seems that `dinghy`'s use of `jinja2` isn't compatible with all versions. The first system I tried it on had `jinja2==2.10.1` installed and gave this error:

```
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/jgerity/repos/dinghy-src/src/dinghy/__main__.py", line 7, in <module>
    cli(prog_name="dinghy")
  File "/home/jgerity/.local/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/jgerity/.local/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/jgerity/.local/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/jgerity/.local/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/jgerity/repos/dinghy-src/src/dinghy/cli.py", line 20, in cli
    asyncio.run(make_digests(config_file))
  File "/usr/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/jgerity/repos/dinghy-src/src/dinghy/digest.py", line 411, in make_digests
    await asyncio.gather(*coros)
  File "/home/jgerity/repos/dinghy-src/src/dinghy/digest.py", line 386, in make_digest
    await render_jinja_to_file(
  File "/home/jgerity/repos/dinghy-src/src/dinghy/jinja_helpers.py", line 44, in render_jinja_to_file
    text = render_jinja(template_filename, **variables)
  File "/home/jgerity/repos/dinghy-src/src/dinghy/jinja_helpers.py", line 34, in render_jinja
    jenv = jinja2.Environment(loader=jinja2.FileSystemLoader(Path(__file__).parent))
  File "/usr/lib/python3/dist-packages/jinja2/loaders.py", line 163, in __init__
    self.searchpath = list(searchpath)
TypeError: 'PosixPath' object is not iterable
```

I was able to fix this by adding a `str()` to [`jinja_helpers.py:L34`](https://github.com/nedbat/dinghy/blob/main/src/dinghy/jinja_helpers.py#L34) locally, but later confirmed that the error does not occur on an up-to-date (`3.0.1`) version of `jinja2`. Pinning a suitable version of the library on the modern side of the breaking change would be an alternate resolution.

### Boilerplate info
OS: Ubuntu 20.04.3 LTS
Python: 3.8.10
`dinghy`: 7634164

**Comment by nedbat** [comment]
Fixed in 6836497.  Thanks!
