### ISSUE TITLE
Unhandled `TypeError: 'NoneType' object is not subscriptable` in digest.py

### ISSUE THREAD

**Issue by rpdelaney** [nedbat/dinghy#23]
Ran `dinghy` from afd56128fbd57da682562540eae739aad230c0e8 with no arguments. Configuration below:
```yaml
---
digests:
  - digest: all_open.html
    title: All open items
    since: 1000 weeks
    items:
      - search: org:trussworks is:open is:pr
        title: Open pull requests
      - search: org:trussworks is:open is:issue
        title: Open issues
```
Got a stack trace:
```
﻿﻿Traceback (most recent call last):
  File "/private/tmp/dinghy/dinghy/.venv/bin/dinghy", line 33, in <module>
    sys.exit(load_entry_point('dinghy==0.13.4', 'console_scripts', 'dinghy')())
  File "/private/tmp/dinghy/dinghy/.venv/bin/dinghy", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/Users/ryan/.local/share/asdf/installs/python/3.10.6/lib/python3.10/importlib/metadata/__init__.py", line 171, in load
    module = import_module(match.group('module'))
  File "/Users/ryan/.local/share/asdf/installs/python/3.10.6/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/private/tmp/dinghy/dinghy/.venv/lib/python3.10/site-packages/dinghy/__main__.py", line 7, in <module>
    cli(prog_name="dinghy")
  File "/private/tmp/dinghy/dinghy/.venv/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/private/tmp/dinghy/dinghy/.venv/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/private/tmp/dinghy/dinghy/.venv/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/private/tmp/dinghy/dinghy/.venv/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/private/tmp/dinghy/dinghy/.venv/lib/python3.10/site-packages/dinghy/cli.py", line 59, in cli
    main_run(coro)
  File "/private/tmp/dinghy/dinghy/.venv/lib/python3.10/site-packages/dinghy/cli.py", line 27, in main_run
    return asyncio.run(coro)
  File "/Users/ryan/.local/share/asdf/installs/python/3.10.6/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/Users/ryan/.local/share/asdf/installs/python/3.10.6/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/private/tmp/dinghy/dinghy/.venv/lib/python3.10/site-packages/dinghy/digest.py", line 505, in make_digests_from_config
    await asyncio.gather(*coros)
  File "/private/tmp/dinghy/dinghy/.venv/lib/python3.10/site-packages/dinghy/digest.py", line 466, in make_digest
    results = await asyncio.gather(*coros)
  File "/private/tmp/dinghy/dinghy/.venv/lib/python3.10/site-packages/dinghy/digest.py", line 99, in get_search_results
    entries = await self._process_entries(entries)
  File "/private/tmp/dinghy/dinghy/.venv/lib/python3.10/site-packages/dinghy/digest.py", line 266, in _process_entries
    entries = await asyncio.gather(*map(self._process_entry, entries))
  File "/private/tmp/dinghy/dinghy/.venv/lib/python3.10/site-packages/dinghy/digest.py", line 276, in _process_entry
    await self._process_pull_request(entry)
  File "/private/tmp/dinghy/dinghy/.venv/lib/python3.10/site-packages/dinghy/digest.py", line 372, in _process_pull_request
    kids, _ = self._trim_unwanted_tree(children.values())
  File "/private/tmp/dinghy/dinghy/.venv/lib/python3.10/site-packages/dinghy/digest.py", line 384, in _trim_unwanted_tree
    if self._node_is_interesting(node):
  File "/private/tmp/dinghy/dinghy/.venv/lib/python3.10/site-packages/dinghy/digest.py", line 224, in _node_is_interesting
    and node["author"]["__typename"] == "User"
TypeError: 'NoneType' object is not subscriptable
```

**Comment by rpdelaney** [comment]
Could be; We have >~40 private repos. I tried running it again with `--verbosity DEBUG` but I'm currently rate limited. Will post back if I can learn more about what it's choking on once I get a reset.

**Comment by rpdelaney** [comment]
Related to #24: if I comment `since:` from the digest, it runs to completion without error.

**Comment by rpdelaney** [comment]
I ran it with `--verbosity DEBUG` but I'm not sure how to interpret this. I'm posting it below in case it's useful to you. Next I'll try hacking up the code locally to get more context.

<details>

```
debug: query searchItems(query: 'org:trussworks is:open is:pr updated:>2003-08-25T12:46:03')
debug: query searchItems(query: 'org:trussworks is:open is:issue updated:>2003-08-25T12:46:03')
debug: query searchItems(query: 'org:trussworks is:open is:issue updated:>2003-08-25T12:46:03', after: 'Y3Vyc29yOjEw')
debug: query searchItems(query: 'org:trussworks is:open is:pr updated:>2003-08-25T12:46:03', after: 'Y3Vyc29yOjEw')
debug: query searchItems(query: 'org:trussworks is:open is:issue updated:>2003-08-25T12:46:03', after: 'Y3Vyc29yOjIw')
debug: query searchItems(query: 'org:trussworks is:open is:issue updated:>2003-08-25T12:46:03', after: 'Y3Vyc29yOjMw')
debug: query searchItems(query: 'org:trussworks is:open is:issue updated:>2003-08-25T12:46:03', after: 'Y3Vyc29yOjQw')
debug: query searchItems(query: 'org:trussworks is:open is:issue updated:>2003-08-25T12:46:03', after: 'Y3Vyc29yOjUw')
debug: query searchItems(query: 'org:trussworks is:open is:issue updated:>2003-08-25T12:46:03', after: 'Y3Vyc29yOjYw')
debug: query searchItems(query: 'org:trussworks is:open is:pr updated:>2003-08-25T12:46:03', after: 'Y3Vyc29yOjIw')
debug: query searchItems(query: 'org:trussworks is:open is:issue updated:>2003-08-25T12:46:03', after: 'Y3Vyc29yOjcw')
debug: query searchItems(query: 'org:trussworks is:open is:issue updated:>2003-08-25T12:46:03', after: 'Y3Vyc29yOjgw')
debug: query searchItems(query: 'org:trussworks is:open is:pr updated:>2003-08-25T12:46:03', after: 'Y3Vyc29yOjMw')
debug: query searchItems(query: 'org:trussworks is:open is:issue updated:>2003-08-25T12:46:03', after: 'Y3Vyc29yOjkw')
debug: query searchItems(query: 'org:trussworks is:open is:issue updated:>2003-08-25T12:46:03', after: 'Y3Vyc29yOjEwMA==')
debug: query searchItems(query: 'org:trussworks is:open is:pr updated:>2003-08-25T12:46:03', after: 'Y3Vyc29yOjQw')
debug: query searchItems(query: 'org:trussworks is:open is:issue updated:>2003-08-25T12:46:03', after: 'Y3Vyc29yOjExMA==')
debug: query searchItems(query: 'org:trussworks is:open is:issue updated:>2003-08-25T12:46:03', after: 'Y3Vyc29yOjEyMA==')
debug: query searchItems(query: 'org:trussworks is:open is:pr updated:>2003-08-25T12:46:03', after: 'Y3Vyc29yOjUw')
debug: query searchItems(query: 'org:trussworks is:open is:issue updated:>2003-08-25T12:46:03', after: 'Y3Vyc29yOjEzMA==')
debug: query searchItems(query: 'org:trussworks is:open is:issue updated:>2003-08-25T12:46:03', after: 'Y3Vyc29yOjE0MA==')
debug: query searchItems(query: 'org:trussworks is:open is:pr updated:>2003-08-25T12:46:03', after: 'Y3Vyc29yOjYw')
debug: query searchItems(query: 'org:trussworks is:open is:issue updated:>2003-08-25T12:46:03', after: 'Y3Vyc29yOjE1MA==')
debug: query searchItems(query: 'org:trussworks is:open is:issue updated:>2003-08-25T12:46:03', after: 'Y3Vyc29yOjE2MA==')
debug: query searchItems(query: 'org:trussworks is:open is:pr updated:>2003-08-25T12:46:03', after: 'Y3Vyc29yOjcw')
debug: query searchItems(query: 'org:trussworks is:open is:issue updated:>2003-08-25T12:46:03', after: 'Y3Vyc29yOjE3MA==')
debug: query searchItems(query: 'org:trussworks is:open is:issue updated:>2003-08-25T12:46:03', after: 'Y3Vyc29yOjE4MA==')
debug: query searchItems(query: 'org:trussworks is:open is:pr updated:>2003-08-25T12:46:03', after: 'Y3Vyc29yOjgw')
debug: query searchItems(query: 'org:trussworks is:open is:issue updated:>2003-08-25T12:46:03', after: 'Y3Vyc29yOjE5MA==')
debug: query searchItems(query: 'org:trussworks is:open is:pr updated:>2003-08-25T12:46:03', after: 'Y3Vyc29yOjkw')
debug: query searchItems(query: 'org:trussworks is:open is:issue updated:>2003-08-25T12:46:03', after: 'Y3Vyc29yOjIwMA==')
debug: query searchItems(query: 'org:trussworks is:open is:issue updated:>2003-08-25T12:46:03', after: 'Y3Vyc29yOjIxMA==')
debug: query searchItems(query: 'org:trussworks is:open is:pr updated:>2003-08-25T12:46:03', after: 'Y3Vyc29yOjEwMA==')
debug: query searchItems(query: 'org:trussworks is:open is:issue updated:>2003-08-25T12:46:03', after: 'Y3Vyc29yOjIyMA==')
debug: query searchItems(query: 'org:trussworks is:open is:pr updated:>2003-08-25T12:46:03', after: 'Y3Vyc29yOjExMA==')
debug: query searchItems(query: 'org:trussworks is:open is:issue updated:>2003-08-25T12:46:03', after: 'Y3Vyc29yOjIzMA==')
debug: query searchItems(query: 'org:trussworks is:open is:issue updated:>2003-08-25T12:46:03', after: 'Y3Vyc29yOjI0MA==')
debug: query searchItems(query: 'org:trussworks is:open is:pr updated:>2003-08-25T12:46:03', after: 'Y3Vyc29yOjEyMA==')
debug: query searchItems(query: 'org:trussworks is:open is:issue updated:>2003-08-25T12:46:03', after: 'Y3Vyc29yOjI1MA==')
debug: query searchItems(query: 'org:trussworks is:open is:issue updated:>2003-08-25T12:46:03', after: 'Y3Vyc29yOjI2MA==')
debug: query searchItems(query: 'org:trussworks is:open is:pr updated:>2003-08-25T12:46:03', after: 'Y3Vyc29yOjEzMA==')
debug: query searchItems(query: 'org:trussworks is:open is:issue updated:>2003-08-25T12:46:03', after: 'Y3Vyc29yOjI3MA==')
debug: query searchItems(query: 'org:trussworks is:open is:issue updated:>2003-08-25T12:46:03', after: 'Y3Vyc29yOjI4MA==')
debug: query searchItems(query: 'org:trussworks is:open is:pr updated:>2003-08-25T12:46:03', after: 'Y3Vyc29yOjE0MA==')
debug: query searchItems(query: 'org:trussworks is:open is:issue updated:>2003-08-25T12:46:03', after: 'Y3Vyc29yOjI5MA==')
debug: query searchItems(query: 'org:trussworks is:open is:issue updated:>2003-08-25T12:46:03', after: 'Y3Vyc29yOjMwMA==')
debug: query searchItems(query: 'org:trussworks is:open is:pr updated:>2003-08-25T12:46:03', after: 'Y3Vyc29yOjE1MA==')
debug: query searchItems(query: 'org:trussworks is:open is:issue updated:>2003-08-25T12:46:03', after: 'Y3Vyc29yOjMxMA==')
debug: query searchItems(query: 'org:trussworks is:open is:pr updated:>2003-08-25T12:46:03', after: 'Y3Vyc29yOjE2MA==')
debug: query searchItems(query: 'org:trussworks is:open is:issue updated:>2003-08-25T12:46:03', after: 'Y3Vyc29yOjMyMA==')
debug: query searchItems(query: 'org:trussworks is:open is:issue updated:>2003-08-25T12:46:03', after: 'Y3Vyc29yOjMzMA==')
debug: query searchItems(query: 'org:trussworks is:open is:pr updated:>2003-08-25T12:46:03', after: 'Y3Vyc29yOjE3MA==')
debug: query searchItems(query: 'org:trussworks is:open is:issue updated:>2003-08-25T12:46:03', after: 'Y3Vyc29yOjM0MA==')
debug: query searchItems(query: 'org:trussworks is:open is:pr updated:>2003-08-25T12:46:03', after: 'Y3Vyc29yOjE4MA==')
debug: query searchItems(query: 'org:trussworks is:open is:issue updated:>2003-08-25T12:46:03', after: 'Y3Vyc29yOjM1MA==')
debug: query searchItems(query: 'org:trussworks is:open is:pr updated:>2003-08-25T12:46:03', after: 'Y3Vyc29yOjE5MA==')
debug: query searchItems(query: 'org:trussworks is:open is:pr updated:>2003-08-25T12:46:03', after: 'Y3Vyc29yOjIwMA==')
debug: query searchItems(query: 'org:trussworks is:open is:pr updated:>2003-08-25T12:46:03', after: 'Y3Vyc29yOjIxMA==')
debug: query searchItems(query: 'org:trussworks is:open is:pr updated:>2003-08-25T12:46:03', after: 'Y3Vyc29yOjIyMA==')
debug: Remaining graphql rate limit: 4868 of 5000, next reset at 13:27:10
Traceback (most recent call last):
  File "/private/tmp/dinghy/dinghy/.venv/bin/dinghy", line 33, in <module>
    sys.exit(load_entry_point('dinghy==0.13.4', 'console_scripts', 'dinghy')())
  File "/private/tmp/dinghy/dinghy/.venv/bin/dinghy", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/Users/ryan/.local/share/asdf/installs/python/3.10.6/lib/python3.10/importlib/metadata/__init__.py", line 171, in load
    module = import_module(match.group('module'))
  File "/Users/ryan/.local/share/asdf/installs/python/3.10.6/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/private/tmp/dinghy/dinghy/.venv/lib/python3.10/site-packages/dinghy/__main__.py", line 7, in <module>
    cli(prog_name="dinghy")
  File "/private/tmp/dinghy/dinghy/.venv/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/private/tmp/dinghy/dinghy/.venv/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/private/tmp/dinghy/dinghy/.venv/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/private/tmp/dinghy/dinghy/.venv/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/private/tmp/dinghy/dinghy/.venv/lib/python3.10/site-packages/dinghy/cli.py", line 59, in cli
    main_run(coro)
  File "/private/tmp/dinghy/dinghy/.venv/lib/python3.10/site-packages/dinghy/cli.py", line 27, in main_run
    return asyncio.run(coro)
  File "/Users/ryan/.local/share/asdf/installs/python/3.10.6/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/Users/ryan/.local/share/asdf/installs/python/3.10.6/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/private/tmp/dinghy/dinghy/.venv/lib/python3.10/site-packages/dinghy/digest.py", line 505, in make_digests_from_config
    await asyncio.gather(*coros)
  File "/private/tmp/dinghy/dinghy/.venv/lib/python3.10/site-packages/dinghy/digest.py", line 466, in make_digest
    results = await asyncio.gather(*coros)
  File "/private/tmp/dinghy/dinghy/.venv/lib/python3.10/site-packages/dinghy/digest.py", line 99, in get_search_results
    entries = await self._process_entries(entries)
  File "/private/tmp/dinghy/dinghy/.venv/lib/python3.10/site-packages/dinghy/digest.py", line 266, in _process_entries
    entries = await asyncio.gather(*map(self._process_entry, entries))
  File "/private/tmp/dinghy/dinghy/.venv/lib/python3.10/site-packages/dinghy/digest.py", line 276, in _process_entry
    await self._process_pull_request(entry)
  File "/private/tmp/dinghy/dinghy/.venv/lib/python3.10/site-packages/dinghy/digest.py", line 372, in _process_pull_request
    kids, _ = self._trim_unwanted_tree(children.values())
  File "/private/tmp/dinghy/dinghy/.venv/lib/python3.10/site-packages/dinghy/digest.py", line 384, in _trim_unwanted_tree
    if self._node_is_interesting(node):
  File "/private/tmp/dinghy/dinghy/.venv/lib/python3.10/site-packages/dinghy/digest.py", line 224, in _node_is_interesting
    and node["author"]["__typename"] == "User"
TypeError: 'NoneType' object is not subscriptable

```

</details>

**Comment by rpdelaney** [comment]
`node.["url"]` goes 🔒 [here](https://github.com/trussworks/legendary-waddle-dev/pull/92#issuecomment-668507489). The user posting the comment has been deleted, as shown in this screenshot:

![Screen Shot 2022-10-24 at 13 20 58](https://user-images.githubusercontent.com/1139517/197587259-d78a77b2-f445-497b-9126-1de78d284f3d.png)

That probably explains why the comment has no author. Here's `node` (contents truncated because the comment body is very long):

```python
{'id': 'MDEyOklzc3VlQ29tbWVudDY2ODUwNzQ4OQ==', 'bodyText': REDACTED, 'updatedAt': '2020-08-04T10:07:12Z', 'author': None, 'url': 'https://github.com/trussworks/legendary-waddle-dev/pull/92#issuecomment-668507489'}
```

**Comment by nedbat** [comment]
Got it. I had code to deal with @ghost for PR and issue authors, but not comment authors...

**Comment by nedbat** [comment]
I think I've fixed it in the nedbat/bug23 branch.  Can you give it a try?
```
pip install git+https://github.com/nedbat/dinghy@nedbat/bug23
```

**Comment by nedbat** [comment]
Fixed in 730227e.

**Comment by nedbat** [comment]
This is now released as part of [dinghy 0.14.0](https://pypi.org/project/dinghy/0.14.0).
